//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanumanInstitute.YangDownloader.Properties {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HanumanInstitute.YangDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        internal static string NoStreamInfo {
            get {
                return ResourceManager.GetString("NoStreamInfo", resourceCulture);
            }
        }
        
        internal static string SetPreferredFormats {
            get {
                return ResourceManager.GetString("SetPreferredFormats", resourceCulture);
            }
        }
        
        internal static string Querying {
            get {
                return ResourceManager.GetString("Querying", resourceCulture);
            }
        }
        
        internal static string DestinationMissing {
            get {
                return ResourceManager.GetString("DestinationMissing", resourceCulture);
            }
        }
        
        internal static string DestinationDoesNotExist {
            get {
                return ResourceManager.GetString("DestinationDoesNotExist", resourceCulture);
            }
        }
        
        internal static string NoStreamSelected {
            get {
                return ResourceManager.GetString("NoStreamSelected", resourceCulture);
            }
        }
        
        internal static string MuxedAudio {
            get {
                return ResourceManager.GetString("MuxedAudio", resourceCulture);
            }
        }
        
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
    }
}
