global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using HanumanInstitute.Common;
global using HanumanInstitute.Common.Services;
global using HanumanInstitute.MediaPlayer.Avalonia.Bass;
global using HanumanInstitute.Validators;
global using ReactiveUI.Fody.Helpers;
