//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergenceGuardian.NaturalGroundingPlayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaRating
    {
        public System.Guid MediaId { get; set; }
        public System.Guid RatingId { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Depth { get; set; }
    
        public virtual Media Medium { get; set; }
        public virtual RatingCategory RatingCategory { get; set; }
    }
}
