//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmergenceGuardian.NaturalGroundingPlayer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaCategory
    {
        public MediaCategory()
        {
            this.Name = "";
            this.Folder = "";
            this.Media = new HashSet<Media>();
        }
    
        public System.Guid MediaCategoryId { get; set; }
        public int MediaTypeId { get; set; }
        public string Name { get; set; }
        public string Folder { get; set; }
    
        public virtual ICollection<Media> Media { get; set; }
    }
}
