#!/bin/bash
set -e

./publish-osx Player432Hz osx-x64
# ./publish-osx Player432Hz osx-arm64

./publish-osx Converter432Hz osx-x64
# ./publish-osx Converter432Hz osx-arm64

./publish-osx PowerliminalsPlayer osx-x64
# ./publish-osx PowerliminalsPlayer osx-arm64

./publish-osx YangDownloader osx-x64
# ./publish-osx YangDownloader osx-arm64
