global using System;
global using System.Collections;
global using System.Collections.ObjectModel;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using Avalonia;
global using HanumanInstitute.Common;
global using HanumanInstitute.Common.Avalonia;
global using HanumanInstitute.Common.Services;
global using HanumanInstitute.Player432Hz.Business;
global using HanumanInstitute.Player432Hz.Models;
global using HanumanInstitute.Player432Hz.ViewModels;
global using HanumanInstitute.Validators;
global using System.Reactive;
global using ReactiveUI.Fody.Helpers;
global using RxCommandUnit = ReactiveUI.ReactiveCommand<System.Reactive.Unit, System.Reactive.Unit>;
global using static System.FormattableString; 
