//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingCategory
    {
        public RatingCategory()
        {
            this.MediaRatings = new HashSet<MediaRating>();
        }
    
        public System.Guid RatingId { get; set; }
        public string Name { get; set; }
        public bool Custom { get; set; }
    
        public virtual ICollection<MediaRating> MediaRatings { get; set; }
    }
}
